export const collegeNames = [
  "Malaviya National Institute of Technology, Jaipur",
  "Rajasthan Technical University, Kota",
  "Government Engineering College, Ajmer",
  "Government Engineering College, Bikaner",
  "Government Engineering College, Jhalawar",
  "Government Engineering College, Bharatpur",
  "Government Engineering College, Banswara",
  "University College of Engineering, RTU, Kota",
  "College of Technology and Engineering, Udaipur",
  "Government Women Engineering College, Ajmer",
  "MBM Engineering College, Jodhpur",
  "Arya College of Engineering and IT, Jaipur",
  "SKIT (Swami Keshvanand Institute of Technology), Jaipur",
  "Jaipur Engineering College and Research Centre (JECRC), Jaipur",
  "Poornima College of Engineering, Jaipur",
  "Manipal University, Jaipur",
  "JK Lakshmipat University, Jaipur",
  "Mody University of Science and Technology, Sikar",
  "LNM Institute of Information Technology (LNMIIT), Jaipur",
  "Global Institute of Technology, Jaipur",
];
